name: KingdomsGameplay
main: fr.tobast.bukkit.kingdomsgameplay.KingdomsGameplay
version: 0.9
author: Tobast

commands:
    zone:
        description: Prints the zone type.
        usage: /zone
        permission: KingdomsGameplay.zone
        permission-message: You don't have the permission to do this!
    team:
        description: Prints a player team
        usage: /team player
        permission: KingdomsGameplay.team
        permission-message: You don't have the permission to do this!
    daynum:
        description: Prints the current day number
        usage: /daynum
        permission: KingdomsGameplay.daynum
        permission-message: You don't have the permission to do this!
    teamset:
        description: Sets a player team
        usage: /teamset player (B|R)
        permission: KingdomsGameplay.admin.teamset
        permission-message: You don't have the permission to do this!

